### ISSUE TITLE
New package for snapshots from ROCMs own fork?

### ISSUE THREAD

**Issue by justinkb** [rocm-arch/tensorflow-rocm#34]
Seems like a good idea, since it looks like upstream tensorflow hasn't merged any RDNA2 changes yet

Currently building from this branch https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/tree/r2.7-rocm-enhanced

**Comment by acxz** [comment]
That does seem like a good idea, however this package is meant to follow official tensorflow built under ROCm and not ROCm's fork per se.
The best way to go about this would be to create a new package that is based off of amd's fork. However, since amd is eventually upstreaming to the official tensorflow repo the package will eventually be phased out. If you're so inclined I'd suggest you make a PKGBUILD for the new package and I can create a repo for it in this org, giving u collaborator/aur push access for that package.

As of now, however, I'll close this issue. Since this is not a priority for this repo.
