### ISSUE TITLE
v.2.9.1 failing to build, roctracer.h not found

### ISSUE THREAD

**Issue by Keridos** [rocm-arch/tensorflow-rocm#41]
See partial build log here: https://gist.github.com/Keridos/3bd548946e8458dc8c06c604ea21e373

**Comment by Keridos** [comment]
These dependencies are missing: roctracer, hipsolver and gcc-11.
Also you need to manually to either symlink gcc and g++ from gcc-11 in /usr/local/bin or adjust the path to /opt/gcc-11/bin/

**Comment by petronny** [comment]
> These dependencies are missing: roctracer, hipsolver and gcc-11.

Hi, will these dependencies be added to the PKGBUILD soon?

**Comment by acxz** [comment]
`hipsolver` is included in `rocm-hip-sdk` which is already a dep, and `roctracer` has been added with 10a3da4

As for now `gcc11`, I'm not sure if that should be added as the upstream PKGBUILD doesn't have that in its depends.

If there are still issues with dependencies please open another issue. Or if you think `gcc11` should be added, since the build fails otherwise than just comment and I'll add it in temporarily while this PKGBUILD is on the AUR.
